### ISSUE TITLE
Github actions research

### ISSUE THREAD

**Issue by MarcinusX** [Fidev-io/framy#1]
We want to research what can and can't we do with Github Actions
- [x] Create a new hello world project
- [x] Try to run tests in Github Actions (can be on commit)
- [x] Build locally as macOS app
- [x] Run integration test locally
- [x] Run integration test on build app on the machine
- [x] Make a screenshot locally in the automated test
- [x] Make a screenshot on the machine
- [x] Try to somehow export the screenshot - I'm not sure if it's possible

**How to build an app on the machine?** 
I think what we can do is use a master branch where we can run apps on macOS.
This means we technically should be able to just run the app on the macOS machine and run integration tests on it. :)

The general idea is to have sth like that:
```
name: Integration test
on: commit(???)
jobs:
  integration-test:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Flutter
        uses: subosito/flutter-action@v1.3.0
        with:
          channel: 'master'
      - run: flutter drive --target=test_driver/app.dart --release
```
What we want to happen is run automated tests as macOS app.
