### ISSUE TITLE
YAML configuration

### ISSUE THREAD

**Issue by MarcinusX** [Fidev-io/framy#13]
Possible configurations:
Use (or not use) SingleChildScrollView + Column on a page.
Use (or not use) some package?

**Comment by MarcinusX** [comment]
Or maybe sth like:
```yaml
framy:
  material_components:
    show: false
```
